jobs:

  - name: deploy-rancheros-rancher_runCI
    type: runCI
    steps:
      - OUT: rancher_app_img

  - name: rancher_deploy_private_image
    type: runSh
    steps:
      # This will automatically set the environment variables needed by rancher-compose
      - IN: rancher_app_cliconfig
      - IN: rancher_app_gitRepo
      - IN: rancher_app_img
      - TASK:
        - script: |
            pushd $(shipctl get_resource_state "rancher_app_gitRepo")/rancher-config
              # Download the rancher-compose CLI. The CLI can also be checked in statically into the
              # rancher-config directory.
              wget -qO- https://releases.rancher.com/compose/v0.12.5/rancher-compose-linux-amd64-v0.12.5.tar.gz | tar xvz
              ./rancher-compose-v0.12.5/rancher-compose --p $STACK_NAME --verbose up -d --force-upgrade --pull --confirm-upgrade $SERVICE_NAME
            popd
